### ISSUE TITLE
Route encoding isomorphism checks

### ISSUE THREAD

**Issue by srid** [EmaApps/ema#78]
Use something like [smallcheck](https://hackage.haskell.org/package/smallcheck) to check the isomorphism property of encodeRoute and decodeRoute at runtime.

**Comment by srid** [comment]
We may be able to obviate these checks by treating route decoding as parsing, and route encoding as pretty-printing. Then this paper becomes relevant: https://www.mathematik.uni-marburg.de/~rendel/rendel10invertible.pdf

**Comment by ju1m** [comment]
@srid, this would be a great move! I've been playing with invertible syntax techniques like the one in Rendel's paper and the one in Kiselyov's [PrintScanf.hs](https://okmij.org/ftp/typed-formatting/PrintScanF.txt) cited by Rendel. Both are equivalent, just using a different encoding (Kiselyov's uses `repr (a -> k) k` to pass/request function arguments instead of tuples, whereas Rendel's uses a simpler `repr a` where `a` can be a tuple or Either). I should mention that although it's using a type-level encoding, [Servant](https://docs.servant.dev/) also amounts to a kind of invertible syntax technique, just a slower and more cumbersome one IMHO :P

A few comments from the top of my head:
* I find the `repr a` syntax (like in Rendel's) less involved, and since most real use cases amount to supply a datatype as input or get a datatype as output, there's no real need for supplying anonymous arguments or a continuation consuming anonymous arguments as Kiselyov's does.
* Maybe I should, but so far I've not embraced Rendel's partial isomorphisms (`data Iso α β = Iso (α → Maybe β ) (β → Maybe α)`) generated by `TemplateHaskell`, AFAICS I do the same with total isomorphisms (`data Iso a b = Iso { a2b :: a->b, b2a :: b->a }`) and either of tuples (`adt = (<%>) (Iso adtOfeot eotOfadt)`, where `(<%>)` is my `IsoFunctor` operator), using `GHC.Generics` to generate the `adtOfeot` injection and `eotOfadt` projection to/from the wanted datatype, almost like what [generics-sop](https://hackage.haskell.org/package/generics-sop) or [generics-eot](https://hackage.haskell.org/package/generics-eot) do, no idea which technique performs the best.
* I reckon Rendel's needs partial isomorphisms to handle recursive syntaxes, whereas I handle those by using something like Gill's [observable sharing](https://doi.org/10.1145/1596638.1596653).

Sorry if those comments are too technical, I do not expect you to understand them until you've actually dived into invertible syntax techniques.

FYI, I gather the crux of my experiments in the [symantic-base](https://hackage.haskell.org/package/symantic-base) package and the other bit-rotting [symantic-*](https://hackage.haskell.org/user/julm) packages, most are likely broken by my lack of time to update them to the latest `symantic-base`, but well, they were somehow working to some extent back then. Though I've not taken the time to convert it from the `repr (a -> k) k` encoding to the `repr a` encoding, you may find interesting bits in [symantic-http](https://hackage.haskell.org/package/symantic-http) for your problem at hand.

Hope this helps you to see a bit further where this can lead Ema, and that I've not said too much mistakes.. no time to double check, family duty calls :s

**Comment by ju1m** [comment]
> I do wonder if the `PartialIsoEnumerableWithCtx` can be improved somehow using the above ideas you mentioned.

@srid, please see: git clone https://git.code.sourcephile.fr/~julm/webc
where I've written you a little demo applying those ideas to the implementation of `encode`, `decode` and `generate` (this last one is kinda like `allRoutes`, though not exactly the same because I've been trying something else along the way):

```haskell
encode :: Encoder a -> a -> [Slug]
decode :: Decoder a -> [Slug] -> Either DecoderError
generate :: Generator a -> Forest (GeneratorNode a)
```
The main idea of **symantics** (aka. tagless-final) is to use type-classes to define **syntax** combinators, and multiple class instances to define an interpreter per wanted **semantic** (eg. here: `Decoder`, `Encoder`, `Generator`).
Then, defining a `site` term using the syntax combinators give use a polymorphic `repr` type, instantiable to each one of those interpreters.

You may want to use `nix flake lock --update-input nixpkgs` before `direnv allow` to use your local nixpkgs, then `make tests` should compile and run some tests.

Hope this helps. Let me know if you have questions.

PS: To avoid making this demo too big I've not included any optimization pass on the combinators (eg. merging the common `literalSlug`s prefixes between alternative branches). But that remains possible, by first instantiating the tagless combinators to data constructors in order to be able to pattern-match them, and them going the other way around to get the tagless combinators back.

**Comment by srid** [comment]
> @ju1m Thanks for the references! Not sure if I'll have time to go over all of these right now, but I got something tangential to this in #81

By the way, just for completeness' sake, I should state that #81 now uses a `Prism'` as route encoder, specifically `Prism' FilePath r`. Again, I'm unsure if this is the "right" approach, but does the job in a simple fashion. Admittedly I haven't delved deeper into your ideas @ju1m ...

One problem with the prism approach is that you can end up producing unlawful prisms. But this is what `Check.hs` aims to catch, but maybe there are better ways to solve this.
